# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.9

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /root/githubfile/coroutine

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /root/githubfile/coroutine

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /root/githubfile/coroutine/CMakeFiles /root/githubfile/coroutine/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /root/githubfile/coroutine/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named maintest

# Build rule for target.
maintest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 maintest
.PHONY : maintest

# fast build rule for target.
maintest/fast:
	$(MAKE) -f CMakeFiles/maintest.dir/build.make CMakeFiles/maintest.dir/build
.PHONY : maintest/fast

#=============================================================================
# Target rules for targets named COROUTINE_LIB

# Build rule for target.
COROUTINE_LIB: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 COROUTINE_LIB
.PHONY : COROUTINE_LIB

# fast build rule for target.
COROUTINE_LIB/fast:
	$(MAKE) -f CMakeFiles/COROUTINE_LIB.dir/build.make CMakeFiles/COROUTINE_LIB.dir/build
.PHONY : COROUTINE_LIB/fast

coroutine.o: coroutine.cpp.o

.PHONY : coroutine.o

# target to build an object file
coroutine.cpp.o:
	$(MAKE) -f CMakeFiles/maintest.dir/build.make CMakeFiles/maintest.dir/coroutine.cpp.o
	$(MAKE) -f CMakeFiles/COROUTINE_LIB.dir/build.make CMakeFiles/COROUTINE_LIB.dir/coroutine.cpp.o
.PHONY : coroutine.cpp.o

coroutine.i: coroutine.cpp.i

.PHONY : coroutine.i

# target to preprocess a source file
coroutine.cpp.i:
	$(MAKE) -f CMakeFiles/maintest.dir/build.make CMakeFiles/maintest.dir/coroutine.cpp.i
	$(MAKE) -f CMakeFiles/COROUTINE_LIB.dir/build.make CMakeFiles/COROUTINE_LIB.dir/coroutine.cpp.i
.PHONY : coroutine.cpp.i

coroutine.s: coroutine.cpp.s

.PHONY : coroutine.s

# target to generate assembly for a file
coroutine.cpp.s:
	$(MAKE) -f CMakeFiles/maintest.dir/build.make CMakeFiles/maintest.dir/coroutine.cpp.s
	$(MAKE) -f CMakeFiles/COROUTINE_LIB.dir/build.make CMakeFiles/COROUTINE_LIB.dir/coroutine.cpp.s
.PHONY : coroutine.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/maintest.dir/build.make CMakeFiles/maintest.dir/main.cpp.o
	$(MAKE) -f CMakeFiles/COROUTINE_LIB.dir/build.make CMakeFiles/COROUTINE_LIB.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/maintest.dir/build.make CMakeFiles/maintest.dir/main.cpp.i
	$(MAKE) -f CMakeFiles/COROUTINE_LIB.dir/build.make CMakeFiles/COROUTINE_LIB.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/maintest.dir/build.make CMakeFiles/maintest.dir/main.cpp.s
	$(MAKE) -f CMakeFiles/COROUTINE_LIB.dir/build.make CMakeFiles/COROUTINE_LIB.dir/main.cpp.s
.PHONY : main.cpp.s

schedule.o: schedule.cpp.o

.PHONY : schedule.o

# target to build an object file
schedule.cpp.o:
	$(MAKE) -f CMakeFiles/maintest.dir/build.make CMakeFiles/maintest.dir/schedule.cpp.o
	$(MAKE) -f CMakeFiles/COROUTINE_LIB.dir/build.make CMakeFiles/COROUTINE_LIB.dir/schedule.cpp.o
.PHONY : schedule.cpp.o

schedule.i: schedule.cpp.i

.PHONY : schedule.i

# target to preprocess a source file
schedule.cpp.i:
	$(MAKE) -f CMakeFiles/maintest.dir/build.make CMakeFiles/maintest.dir/schedule.cpp.i
	$(MAKE) -f CMakeFiles/COROUTINE_LIB.dir/build.make CMakeFiles/COROUTINE_LIB.dir/schedule.cpp.i
.PHONY : schedule.cpp.i

schedule.s: schedule.cpp.s

.PHONY : schedule.s

# target to generate assembly for a file
schedule.cpp.s:
	$(MAKE) -f CMakeFiles/maintest.dir/build.make CMakeFiles/maintest.dir/schedule.cpp.s
	$(MAKE) -f CMakeFiles/COROUTINE_LIB.dir/build.make CMakeFiles/COROUTINE_LIB.dir/schedule.cpp.s
.PHONY : schedule.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... maintest"
	@echo "... COROUTINE_LIB"
	@echo "... coroutine.o"
	@echo "... coroutine.i"
	@echo "... coroutine.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... schedule.o"
	@echo "... schedule.i"
	@echo "... schedule.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

